"""empty message

Revision ID: d866cf5b3ad3
Revises: 
Create Date: 2019-06-04 21:33:04.340493

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd866cf5b3ad3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dados_novos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('bairro', sa.String(length=100), nullable=False),
    sa.Column('dorms', sa.Integer(), nullable=False),
    sa.Column('banhos', sa.Integer(), nullable=False),
    sa.Column('vagas', sa.Integer(), nullable=False),
    sa.Column('area', sa.Float(), nullable=False),
    sa.Column('cond', sa.String(length=10), nullable=False),
    sa.Column('valor', sa.String(length=10), nullable=False),
    sa.Column('cidade', sa.String(length=60), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(length=30), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('senha', sa.String(length=60), nullable=False),
    sa.Column('imagem_perfil', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('consultas',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('dorms', sa.Integer(), nullable=False),
    sa.Column('banhos', sa.Integer(), nullable=False),
    sa.Column('vagas', sa.Integer(), nullable=False),
    sa.Column('area', sa.Float(), nullable=False),
    sa.Column('descr', sa.String(length=30), nullable=False),
    sa.Column('data', sa.Date(), nullable=False),
    sa.Column('valor', sa.String(), nullable=False),
    sa.Column('cidade', sa.String(length=60), nullable=True),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('consultas')
    op.drop_table('usuarios')
    op.drop_table('dados_novos')
    # ### end Alembic commands ###
